### PR TITLE
add filter by ExclusiveStartShardId for listShards

### PR DESCRIPTION
**Pull request by EugeneYushin**
issue details:
https://github.com/mhart/kinesalite/issues/76

### CODE REVIEW

**Comment by EugeneYushin** [comment]
@mhart please, can you take a look on this?

**Comment by tweise** [comment]
@mhart could you please take a look or let us know if there is a different maintainer that we can ping?

**Comment by EugeneYushin** [comment]
@mhart Have you had a chance to look at this PR?
Do you know anyone who can review in case you have no spare time for this?
Regards

**Comment by mhart** [comment]
Thanks for this – apologies for the delay in getting it out. Committed in https://github.com/mhart/kinesalite/commit/791f782e36fae826bc8a99b14cceb4419569dbc1 and published in v1.15.0 – although I suggest upgrading to 2.x because `level-sublevel` has been deprecated.

Thanks again!

**Pull request closed without merging**
