### PR TITLE
Started reading your intro...

### PR DESCRIPTION
**Pull request by atrauzzi**
Sorry, this is just such a common spelling error.

https://trends.google.com/trends/explore?q=focused,focussed

❤️

### CODE REVIEW

**Comment by mhart** [comment]
It's not a spelling error. https://en.wiktionary.org/wiki/focussed

**Comment by atrauzzi** [comment]
That doesn't seem to support your point as well as you might be thinking  Regardless, I think you'll find that the majority of usage despite British convention favours `focused` and that most people will do a double take on it.

Whatever, just helping you put your best foot forward in your opening paragraph!

(BTW, I'm Canadian, so I do things like "behaviour", and "neighbour", I know the pain here.)

**Comment by mhart** [comment]
> That doesn't seem to support your point as well as you might be thinking

The fact that it's how we spell the word doesn't support my point that it's not a spelling error? What? Would you have "corrected" it if I had written behaviour or neighbour? I'm Australian. That's how we spell the word! SMH

**Comment by atrauzzi** [comment]
Yikes man, I think you're taking this the wrong way.

**Pull request closed without merging**
