### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by traviswdev**
Irony: "focussed on correctness" ... nice.

### CODE REVIEW

**Comment by mhart** [comment]
Maybe have a think next time mate before you completely pummel yourself in the face: https://en.wiktionary.org/wiki/focussed

**Comment by traviswdev** [comment]
Thanks! I clicked on your profile and saw "New York", so I assumed you weren't British, my bad!

**Comment by mrspeaker** [comment]
Irony: "Irony: 'focussed on correctness'"... nice. https://en.wiktionary.org/wiki/irony

**Comment by traviswdev** [comment]
I was waiting for some sort of "stupid American, I'm not British, I'm Australian". I guess that works too. You really got me. 

I didn't mean to offend, of course. I meant to help you not look stupid if you unintentionally misspelled something. I'm sorry.

**Pull request closed without merging**
