### PR TITLE
added partial support for ListShards

### PR DESCRIPTION
**Pull request by oriy**
(https://docs.aws.amazon.com/kinesis/latest/APIReference/API_ListShards.html)

* supports listing given StreamName only (NextToken and StreamCreationTimestamp unsupported)

### CODE REVIEW

**Comment by asottile** [comment]
Probably needs a rebase, there's a conflict now

**Comment by oriy** [comment]
@mhart please review
this api call is essential for AWS KCL workflow

**Comment by buremba** [comment]
The newer versions of AWS KCL library uses this API so it's not possible to use Kinesaline for KCL without ListShards API support.

**Comment by mhart** [comment]
Thanks for starting this off! Added some more tests and validation and published as v1.13.0

**Comment by oriy** [comment]
Thanks
Brilliant

**Comment by kailashhd** [comment]
Thanks @mhart and @oriy.

**Pull request merged**
